#!/bin/bash

RCol='\033[33;0m'
Blu='\033[33;34m'

echo ""
# bold Bold High Intens
printf "\n\n\t \033[1;30;31m" 
echo -e "	>>>>  CROSS_COMPILE is automatically select from prebuilt dir"
printf "\033[0m \n\n" 
echo ""

make -j8 ARCH=arm CROSS_COMPILE=../../RK3188_ANDROID4.4.4_r2-SDK_V1.00_20131222/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/bin/arm-eabi- \
$1 $2 $3 $4 $5 


if [ "$1" = "kernel.img" ] ; then
	printf "\n\n\t \033[1;30;31m   cp kernel.img /media/sf_C_DRIVE/RK3188/shcho_img/kernel.4.4.4_r2.img"
	printf "\n\n\t"
#	printf "cp arch/arm/boot/Image /media/shcho2/ccache_build/android_build/rk3188_rk3066_r-box_android4.4.2_sdk/target/product/radxa_rock_pro/kernel"
	printf "\033[0m \n\n" 
	cp kernel.img /media/sf_C_DRIVE/RK3188/shcho_img/kernel.4.4.4_r2.img
#	cp arch/arm/boot/Image /media/shcho2/ccache_build/android_build/rk3188_rk3066_r-box_android4.4.2_sdk/target/product/radxa_rock_pro/kernel
fi

